version: '3.1'
services:
  springboot:
    image: likhithagodina/maven-web-application:{buildNumber}
    restart: always
    ports:
    - 8080:8080
    networks:
    - mavenappbridge
networks:
  mavenappbridge:
