version: '3.1'
services:
  maven-web-app:
    image: likhithagodina/maven-web-app:{buildNumber}
    restart: always
    ports:
    - 8080:8080
    networks:
    - mavenappbridge
networks:
  mavenappbridge:
